### ISSUE TITLE
Class that implements an interface doesn't get output by the cross-compiler

### ISSUE THREAD

**Issue by rolandzwaga** [RandoriAS/randori-compiler#10]
Create an interface then create a class that implements the interface. Compile or build, and you'll see there is no output.

**Comment by labriola** [comment]
This is correct behavior at present. Interfaces do not output. Concept does not exist in destination language

**Comment by teotigraphix** [comment]
@labriola No, its that for some reason a class that implements an interface doesn't output. I think I didn't override something in the ASEmitter, something stupid like an exception.

**Comment by rolandzwaga** [comment]
@labriola  Exactly, what Mike Schmalle says. Its correct that an interface gets ignored, but any class implementing an interface gets skipped, which is incorrect.

**Comment by labriola** [comment]
Check. Got it

**Comment by teotigraphix** [comment]
@rolandzwaga @labriola I tested this directly and it works; ClassC implements IA

I guess I will have to check the plugin when Fred fixes the FileUtils.

``` javascript
if (typeof demo == "undefined")
    var demo = {};
if (typeof demo.foo == "undefined")
    demo.foo = {};

demo.foo.ClassC = function() {
};

demo.foo.ClassC.prototype.get_data = function() {
    return null;
};

demo.foo.ClassC.prototype.set_data = function(value) {
};

demo.foo.ClassC.className = "demo.foo.ClassC";

demo.foo.ClassC.getClassDependencies = function(t) {
    var p;
    return [];
};

demo.foo.ClassC.injectionPoints = function(t) {
    return [];
};
```

**Comment by teotigraphix** [comment]
Issue with new file creation and bug with compiler project.
