### ISSUE TITLE
Bug: Static class reference not making it into getClassDependencies

### ISSUE THREAD

**Issue by renaun** [RandoriAS/randori-compiler#100]
AS3 Classes -

bug/BugF.as:
package bug
{ 
public class BugF
{  
    public function BugF() {  
        addEventListener(BugEvent.SOME_EVENT, null);
    }

```
public function addEventListener(type:String, callback:Function):void { }
```

}
}

bug/BugEvent.as:
package bug
{ 
public class BugEvent
{  
    public static const SOME_EVENT : String = "someEvent";
}
}

Output of BugF JS is this:
if (typeof bug == "undefined")
    var bug = {};

bug.BugF = function() {
    this.addEventListener(bug.BugEvent.SOME_EVENT, null);
};

bug.BugF.prototype.addEventListener = function(type, callback) {
};

bug.BugF.className = "bug.BugF";

bug.BugF.getClassDependencies = function(t) {
    var p;
    return [];
};

bug.BugF.injectionPoints = function(t) {
    return [];
};

But if you run this it will throw and error as it can't find bug.BugEvent. The bug.BugEvent should be placed into the getClassDependenices array.

**Comment by teotigraphix** [comment]
@renaun yeah there are a couple cases where we add dependencies so I will get this, but if its a constant, the compiler should just be putting a string in there.

**Comment by renaun** [comment]
Agreed on the constant thing. It also happens for the case of a parameter in a method as well. So add this method to the class:

public function someHandler(event:Event) {}

**Comment by labriola** [comment]
you can aadd the static dependencies but stop short of method args.... we do not want to do that without significant discussion

**Comment by teotigraphix** [comment]
yeah I was wondering about args as well, seems like it doesn't make sense for javascript

**Comment by labriola** [comment]
YYep, and if we did args the recursive class loading stuff would pretty much undo everything we have working. Need to be careful on sstuff like that. Args shouldn't be needed as they are defined when a method is invoked, not by the method. Also breaks polymorphism, etci

**Comment by teotigraphix** [comment]
This is fixed with the dep, but I still have to work on the constant resolve. I am closing this issue but will work on the resolving later.

commit 69d32d5
