### ISSUE TITLE
AS3 Language Issue: AS3 with only a function in it

### ISSUE THREAD

**Issue by renaun** [RandoriAS/randori-compiler#106]
Here is a valid as3 file:

``` actionscript
package flash.utils
{
public function getTimer():int
{
    return 1;
}
}
```

In the output JS it treats it like a class which I think is wrong. Here is the JS:

``` javascript
/** Compiled by the Randori compiler v0.2.4.11 on Sat Jun 08 15:51:25 PDT 2013 */

if (typeof flash == "undefined")
    var flash = {};
if (typeof flash.utils == "undefined")
    flash.utils = {};

flash.utils.getTimer = function() {
    return 1;
}

flash.utils.getTimer.className = "flash.utils.getTimer";

flash.utils.getTimer.getClassDependencies = function(t) {
    var p;
    return [];
};

flash.utils.getTimer.injectionPoints = function(t) {
    return [];
};
```

When called in JS as flash.utils.getTimer() it throws an JS error of: Object #<Object> has no method 'getTimer'

Not sure what the JS is suppose to be.

**Comment by labriola** [comment]
yes, we came across this before and actually agree it shouldnt be a class (although we still need to deal with dependencies like it is). i am curious about the error you received though and will look. we use package level functions in our unit tests without issue presently

**Comment by teotigraphix** [comment]
@renaun Don't know hat to say about this one. As Mike said we have talked about this and I implemented it the way you see for his unit testing in javascript. So until you guys figure out a solution, I can't really do anything here.

**Comment by renaun** [comment]
looks like its just a JS path issue. Outputted JS was just:
getTimer()
and needs to be:
flash.utils.getTimer()

**Comment by teotigraphix** [comment]
commit 336b89d
