### ISSUE TITLE
Figure out how to build our own builtin.swc

### ISSUE THREAD

**Issue by rolandzwaga** [RandoriAS/randori-compiler#11]
Currently we're using the builtin.swc as provided by Tamarin, which only contains the base types (so no DisplayList or other FlashPlayer native classes).
We need to figure out how to build this swc ourselves so we can add our own base types for Randori.

**Comment by teotigraphix** [comment]
@labriola @rolandzwaga PING :8ball: This needs a reality check whether you plan on putting time into it within the next 2 weeks or not. See issue#20 comment.

**Comment by rolandzwaga** [comment]
Ok, I figured out a way to actually get this working using the Tamarin sources for the native types, compc and some really dirty hacking. But, I have a way of creating this stuff, which even still works in Randori.
Next up will be to create a decent workflow for creating this.
