### ISSUE TITLE
Bug: Class doesn't make it into class dependency path

### ISSUE THREAD

**Issue by renaun** [RandoriAS/randori-compiler#123]
AS3:

``` actionscript
package bug
{ 
public class BugL
{
    public function BugL() {
        var a:* = (true) ? trace : null;
    }

}
}
```

The "trace" class never makes it into the class dependency list

**Comment by teotigraphix** [comment]
@renaun @labriola ok this is getting annoying, I am really trying to NOT put this stuff in the identifier cause then we are going to have an explosion of dependencies where you don't want them.

I will wait to fix this until you try and find more.
