### ISSUE TITLE
Let the Randori compiler, optionally, validate class names in Randori CSS and HTML "data-" attributes. 

### ISSUE THREAD

**Issue by rolandzwaga** [RandoriAS/randori-compiler#14]
Class names for behaviours, mediators and contexts can be added to the CSS and HTML in a Randori project.
In IntelliJ we'll add code completions to make this easier, but to make the circle complete it would be great if the compiler can actually extract these class names and validate them against the actual definitions.
No idea how feasible this is, but putting the issue in here as a wild idea. :)

This functionality should be turned off by default, since behaviors, etc aren't always known @compiletime. So there should be options for ignoring, generating warnings or errors for unresolved class names in CSS and HTML.

**Comment by labriola** [comment]
be cautious with this. validation is great but you are beginning to again assume a fixed project with known bounds which is not always the case. further, the injector config can change any of the definitions to an alternate class. just proceed carefully. our goal is large enterprise where the system is not bounded by a single project or compile time decisions

**Comment by rolandzwaga** [comment]
You are right. Perhaps we should make this one optional, or add the possibility to generate either warnings or errors, depending on what the proejct demands.

**Comment by labriola** [comment]
yes. also remember that mediators and behaviors could be written directly in js. in which case we have no way to validate but are still valid at runtime. so, moral of the story is... be cautious

**Comment by rolandzwaga** [comment]
Clear to me. I've changed the main issue to state that these checks should be optional and need to be able to be turned off completely. Well, they should be turned off by default actually.

**Comment by teotigraphix** [comment]
@rolandzwaga Are you saying I have to parse css and validate? I am a bit confused.

**Comment by rolandzwaga** [comment]
No, this is handled in the IDE for now, no need for compiler functionality. I'm closing this issue for now.
