### ISSUE TITLE
Using a class that is annotated with mode="json" yeilds an empty .as file when used

### ISSUE THREAD

**Issue by rolandzwaga** [RandoriAS/randori-compiler#140]
I have an interop class that looks like this:

[JavaScript(export="false", mode="json", name="Object")]
public class CharacterParam {

```
public function CharacterParam(alpha:Boolean=undefined, casing:Boolean=undefined, pool:String=undefined, symbols:Boolean=undefined) {
    super();
}

public var alpha:Boolean;
public var casing:Boolean;
public var pool:String;
public var symbols:Boolean
```

}

This class is used as a method argument:

public function character(param:CharacterParam=undefined):String;

Now, when I used this in my code like this:

var chance:Chance = new Chance();
chance.character(new CharacterParam(undefined, true, "bla"));

I receive no error, but the JavaScript file that is generated is 0 bytes.
If I remove the param, like this:

var chance:Chance = new Chance();
chance.character();

Everything works.

What I expect to be output would be this:

var chance = new Chance();
chance.character({casing: true, poll: "bla"});

Am I overlooking something really obvious?

I'm using the latest plugin that Fred built yesterday, which was created with almost the very latest compiler sources.

**Comment by teotigraphix** [comment]
commit 02469beaf81bb3537d2672f2eb8318fe15dccf3e 0.2.4.28
