### ISSUE TITLE
Bug: Super default args not being set

### ISSUE THREAD

**Issue by renaun** [RandoriAS/randori-compiler#142]
AS3 classes:

``` actionscript
package bug
{ 
public class BugE extends BugD
{       
    public function BugE() {    
        super("is the best");
    }
}
}
```

``` actionscript
package bug
{ 
public class BugD
{       
    public function BugD(a:String, b:String = "randori") {
        if (b.length > 0)
            a = b;
    }
}
}
```

The outputted JS fro bug.BugE is:

``` javascript
bug.BugE = function() {
    bug.BugD.call(this, "is the best");
};
```

but should be:

``` javascript
bug.BugE = function() {
    bug.BugD.call(this, "is the best" , "randori");
};
```

**Comment by teotigraphix** [comment]
@renaun this has to do with ALL function calls. I am working on a solution. This implementation changed when we removed the if() defaults in a previous impl.

**Comment by renaun** [comment]
other function calls seem to be getting the arguments correctly but the .call seem to act differently

**Comment by teotigraphix** [comment]
you mean defaults work correctly? if you were to use the same scenario above but with normal methods?

**Comment by teotigraphix** [comment]
I know it dosn't work with this `super.foo("something");` but that is a call as well

**Comment by renaun** [comment]
Yeah if I do this in AS3:

var dd:BugD = new BugD("2nd"); 

it correctly creates:

var dd = new bug.BugD("2nd", "randori");

**Comment by teotigraphix** [comment]
BaseA

```
    public function bar(a:String, b:String = "randori"):void
    {
    }
```

BaseB

```
    public function test_bar():void
    {
        bar("foo");
    }
```

Correctly outputs;

```
demo.foo.support.BaseB.prototype.test_bar = function() {
    this.bar("foo", "randori");
}
```

So I was wrong in thinking this has to do with everything.

I might actually know the problem now.

Thanks

**Comment by teotigraphix** [comment]
And yes it just seems to be with the super() calls either a constructor call or a member super call `super.foo()` call

**Comment by teotigraphix** [comment]
commit      1268ece

**Comment by renaun** [comment]
fixed thx
