### ISSUE TITLE
Bug: Double static paths

### ISSUE THREAD

**Issue by renaun** [RandoriAS/randori-compiler#145]
AS3:
Sounds.sndBgMain.play(0, 999);

In the Sounds class it looks like:
public static var sndBgMain:Sound = new Sound();

Is turning into JS:
com.hsharma.hungryHero.Sounds.com.hsharma.hungryHero.Sounds.sndBgMain.play(0, 999);

Expected:
Only one path:
com.hsharma.hungryHero.Sounds.sndBgMain.play(0, 999);

Might be related is this code:
var scale:Number  = Starling.contentScaleFactor;

Starling.contentScaleFactor looks like this in AS3 code:
public static function get contentScaleFactor():Number 
        {
            return sCurrent ? sCurrent.contentScaleFactor : 1.0;
        }

turned into JS:
var scale = starling.core.Starling.starling.core.Starling.get_contentScaleFactor();

**Comment by teotigraphix** [comment]
commit      4184ac4

**Comment by renaun** [comment]
the 2nd part is not fixed:

var scale:Number = Starling.contentScaleFactor;
or
mScaleFactor = scaleFactor > 0 ? scaleFactor : Starling.contentScaleFactor;

Create in JS:
starling.core.Starling.starling.core.Starling.get_contentScaleFactor()
