### ISSUE TITLE
Bug: Missing path on class declaration when in class instantiation

### ISSUE THREAD

**Issue by renaun** [RandoriAS/randori-compiler#146]
AS3:
private function drawGame():void
{
    particleCoffee = new PDParticleSystem(XML(new ParticleAssets.ParticleCoffeeXML()), Texture.fromBitmap(new ParticleAssets.ParticleTexture()));
}

JS:
com.hsharma.hungryHero.screens.InGame.prototype.drawGame = function() {
    com.hsharma.hungryHero.screens.InGame.particleCoffee = new starling.extensions.PDParticleSystem(new com.hsharma.hungryHero.ParticleAssets.ParticleCoffeeXML(), starling.textures.Texture.fromBitmap(new com.hsharma.hungryHero.ParticleAssets.ParticleTexture(), true, false, 1));
}

This class "com.hsharma.hungryHero.ParticleAssets" does not make it into the class path.

The ParticleCoffeeXML on ParticleAssets looks like this in JS:
com.hsharma.hungryHero.ParticleAssets.ParticleCoffeeXML = com.hsharma.hungryHero.ParticleAssets.Embed$ParticleCoffeeXML;

**Comment by teotigraphix** [comment]
commit      4184ac4

**Comment by renaun** [comment]
seems to be fixed
