### ISSUE TITLE
Add gradle build system

### ISSUE THREAD

**Issue by martinopic** [RandoriAS/randori-compiler#15]
In my opinion this would be better than #5 and #6 gradle is usually regarded as more flexible and modern of both maven and ant, moreover it can easily integrate with both, publish on maven repositories (and using maven dependencies) and be used without installing it throuhg gradle wrapper. Working on it.

**Comment by rolandzwaga** [comment]
Fair enough, any kind of build integration is great. So if Gradle comes first, I see no problems with that :) Thanks for the effort!

**Comment by teotigraphix** [comment]
@martinopic I have never used gradle, what does it take to setup and run?

**Comment by martinopic** [comment]
Just download and install this (http://www.gradle.org/installation) you need just a 1.5 JDK as it ships with its own groovy library (mostly written in groovy, the build file itself is groovy).

The nice thing is that through gradle wrapper developers just interested in building don't need to install anything (just need a working JVM). I'm working on a randori gradle plugin, realized that I needed a randori compiler dependency so here I am.

**Comment by teotigraphix** [comment]
basic support added, directory structure changed
