### ISSUE TITLE
Bug: Super being applied to dynamic functions

### ISSUE THREAD

**Issue by renaun** [RandoriAS/randori-compiler#162]
AS3:

``` actionscript
package bug
{ 
public class BugS extends BugT
{
    public function BugS() {
        parseFloat("100");
        var x:Object = new Object();
        num = parseFloat(x.attribute("name"));

        super("test1", 111);
    }
    private var num:Number; 
}
}
```

``` actionscript
package bug
{ 
public class BugT
{
    public function BugT(var1:String, var2:Number, var3:Number = 67, var4:Number = 1532) {

    }
}
}
```

Outputted JS:

``` javascript
bug.BugS = function() {
    this.num = 0;
    parseFloat("100");
    var x = {};
    this.num = parseFloat(x.attribute("name", , 67, 1532));
    bug.BugT.call(this, "test1", 111, 67, 1532);
};
```

The ", , 67, 1532" should not be in the "this.num = parseFloat(x.attribute("name", , 67, 1532));" line of code. The ", , 67, 1532" seems to be coming from the BugT's constructor structure.

**Comment by teotigraphix** [comment]
I have to say, this is probably the finniest bug I have seen yet. Obviously a variable somewhere messing with me.

**Comment by renaun** [comment]
yeah, i forgot to mention this worked fine in 2.4.26, but after that the bug showed up. But that is probably related to that other "super" changes that where made.

**Comment by teotigraphix** [comment]
It has to do with default args in the function call, I already found the bug.

**Comment by teotigraphix** [comment]
commit      dd2c58d
