### ISSUE TITLE
Bug: Path on static method not right

### ISSUE THREAD

**Issue by renaun** [RandoriAS/randori-compiler#165]
AS3 snippets:

``` actionscript
        private static function registerDefaults():void
        {
            register(LINEAR, linear);
        }

        protected static function linear(ratio:Number):Number
        {
            return ratio;
        }
```

Has JS like:

``` javascript
starling.animation.Transitions.register("linear", $createStaticDelegate(this, linear));
```

But should be:

``` javascript
starling.animation.Transitions.register("linear", $createStaticDelegate(this, starling.animation.Transitions.linear));
```

**Comment by teotigraphix** [comment]
Ok some of these things you are running into have to do with when I changed logic from static and runtime deps.

I'm just waiting a day or so while you test these things to work on them all at once.

**Comment by teotigraphix** [comment]
BTW, I have 430 tests and they all pass, so whatever is failing right now I don't have tests for. So this isn't necessarily a bad thing.

**Comment by teotigraphix** [comment]
commit      64bb753
