### ISSUE TITLE
Bug or JS/AS3 limitation: Initilizing Array/Vector

### ISSUE THREAD

**Issue by renaun** [RandoriAS/randori-compiler#166]
AS3 Code:

``` actionscript
var nums:Vector.<Number> = new Vector.<Number>(10);
var objs:Vector.<Object> = new Vector.<Object>(10);
```

Outputted JS:

``` javascript
this.nums = [10];
this.objs = [10];
```

But it really should be something like this:

``` javascript
this.nums = [0,0,0,0,0,0,0,0,0,0];
this.objs = [null,null,null,null,null,null,null,null,null,null];
```

**Comment by teotigraphix** [comment]
Well for a Vector, I know exactly where that is, is the length the only possible arg or can you pass and array also? I forget (I would have to look at the language ref :) ).

**Comment by renaun** [comment]
You can pass in an array to initialize it, so there is a case there too

var vector:Vector.<String> = Vector.<String>(["v1", "v2", "v3"]);

**Comment by teotigraphix** [comment]
commit      ee78d0a
