### ISSUE TITLE
Feature: Factory class for Embeds

### ISSUE THREAD

**Issue by renaun** [RandoriAS/randori-compiler#177]
Added metadata for specific embed factory class.

Take this AS3:

``` actionscript
[Factory(factoryClass="flash.utils.FlashEmbed.getEmbed",type="flash.display.Bitmap")]
[Embed(source = "../startup.jpg")]
private var Background:Class;
```

And create JS like this:

``` javascript
this.Background = flash.utils.FlashEmbed.getEmbed("flash.display.Bitmap", {source: "../startup.jpg"});
```

factoryClass = Factory method class which takes a type and properties
Any metadata properties in the [Embed] end up in the object parameter of the function. Also any other properties in the [Factory] metadata that are not factoryClass or type are added in to the properties object.

**Comment by teotigraphix** [comment]
commit 737ff8d
