### ISSUE TITLE
.swc are not generated to .js

### ISSUE THREAD

**Issue by doublefx** [RandoriAS/randori-compiler#186]
this is what I passed to the compiler:

-library-path=F:/sources/randori/randori-demos-bundle/HMSS/libs/asLib.swc
-source-path=F:/sources/randori/randori-demos-bundle/model/src
-source-path=F:/sources/randori/randori-demos-bundle/service/src
-source-path=F:/sources/randori/randori-demos-bundle/HMSS/src
-sdk-path=F:/sources/randori/randori-sdk
-app-name=randori-demos-bundle
-js-base-path=generated
-js-library-path=generated/lib
-js-classes-as-files=true
-output=F:/sources/randori/randori-demos-bundle/HMSS

asLib.swc is a simple as3 lib containing one simple class.
The code calling this class is generated as well as the inclusion via getRuntimeDependencies but not the asLib.js itself

**Comment by rolandzwaga** [comment]
Randori cannot compile a binary swc, it needs actual AS3 source code to compile.
The only type of swc that can be added dirtectly as a dependency is an interop library, since doesn't require any AS3 to be cross-compiled.
