### ISSUE TITLE
export="false" and name defaults

### ISSUE THREAD

**Issue by labriola** [RandoriAS/randori-compiler#21]
It would be nice if when using export="false", the name defaulted to the full package and class name of the file it was annotating.

Currently, if you mark something export="false" but forget the name, any class using the marked class will not generate.

**Comment by teotigraphix** [comment]
@labriola this doesn't make sense from export = false and use the annotated qualified name. Can you give a concrete code example.

**Comment by labriola** [comment]
Let's say I have this class. Note the name attributes is set to google.maps.Map which is _exactly_ the same as the package and class already.

```
package google.maps {
[JavaScript(export="false",name="google.maps.Map")]
public class Map {
    public function Map( element:HTMLElement, options:MapOptions ) {
    }

    public function setTilt(i:Number):void {

    }

    public function getCenter():LatLng {
        return null;
    }
}
}
```

Elsewhere in my code, I say:

```
var newMap:Map = new Map(someElement, mapOptions);
```

The exported JavaScript is (correctly)

```
var newMap = new google.maps.Map(someElement, mapOptions);
```

However, I have to manually set the name attribute of the class the same as the class and package as noted above. If I don't set the name attribute, the file where i _use_ the Map class (the one where is say this:)

```
var newMap:Map = new Map(someElement, mapOptions);
```

Will be completely empty when I look at the generated JavaScript. It creates the file, but its an empty file.

Mike

**Comment by teotigraphix** [comment]
commit 4f78366ac2afa39aa574f4ba40a9962b74c437c3
