### ISSUE TITLE
Fully test JavaScript export

### ISSUE THREAD

**Issue by teotigraphix** [RandoriAS/randori-compiler#23]
- global, json, proto
- constructor
- constant

Create one Test class, take out regression tests and add them to this class.

**Comment by teotigraphix** [comment]
@labriola Mike, I am working on these tests right now. It has occurred to me, that if you spent 5 minutes writing a comprehensive linear list of functionality of this tag, then I could just test every scenario.

Since I am not actually writing these apps right now, its more like I am guessing since we don't really have a spec sitting around.

**Comment by teotigraphix** [comment]
@labriola Mike PING! if you want this to work good, I need a list from a developer. :8ball: I actually have some time again, so can you get me this.

**Comment by labriola** [comment]
it will be a few days. still at max and trying to juggle a number of things

**Comment by labriola** [comment]
Working on this now, hope to have you a write up of the tag posted here before my day is over

**Comment by labriola** [comment]
Created a wiki page with my expectations for each of these tags. Was a good task as a few things don't work as expected today so we can discuss when you have time

https://github.com/RandoriAS/randori-plugin-intellij/wiki/JavaScript-Compiler-Annotations

**Comment by teotigraphix** [comment]
Thanks for this Mike! That is exactly what I was looking for.

**Comment by teotigraphix** [comment]
BTW

```
//In an ideal world
var x2 = {prop:"7", thing:"8"};

//Also acceptable
var x2 = {};
x2.prop = "7";
x2.thing = "8";
```

During my tests I might actually be able to pull this inline object definition off. It depends if I have the skills.

**Comment by teotigraphix** [comment]
commit 9d5b11e2f0fa533c3dd90f85b49e5de1d359e8b1

[JavaScript] is fully tested, if any bugs come up, create a new issue.
