### ISSUE TITLE
Inner functions fail to generate

### ISSUE THREAD

**Issue by labriola** [RandoriAS/randori-compiler#28]
override protected function onRegister():void {

```
function showMe( counter:int ):void {
  Window.console.log("this is my counter" + counter );
}

for ( var i:int = 0; i<5; i++ ) {
  showMe( i );
}
```

  }

Outputs as:

mediators.IndexMediator.prototype.onRegister = function() {
                ;
                for (var i = 0; i < 5; i++) {
                                showMe(i);
                }
};

**Comment by teotigraphix** [comment]
commit 3b12d06e817b58af0bda85d77012a97b5b60665e
