### ISSUE TITLE
Possible scope delegation issue

### ISSUE THREAD

**Issue by labriola** [RandoriAS/randori-compiler#30]
Consider this class. In the constructor, I invoke methodA of this class and pass method B. I also create a new Delegate test class and invoke method, passing method B but this from the ‘outside’ of the class.

```
public class DelegateTest {
  public function methodA( fn:Function ):void {}
  public function methodB():void {}

  public function DelegateTest() {
    methodA( methodB );

    var dt2:DelegateTest = new DelegateTest();
    dt2.methodA( dt2.methodB );
  }
}
```

Here is the generated constructor:

```
DelegateTest = function() {
    this.methodA($createStaticDelegate(this, this.methodB));
    var dt2 = new DelegateTest();
    dt2.methodA(dt2.methodB);
};
```

So, the first time it wraps methodB in a delegate. In the second example it doesn’t. I have been looking at code too long so maybe I am wrong, Please check me as well on this expectation, but I think this makes more sense:

```
DelegateTest = function() {
    this.methodA($createStaticDelegate(this, this.methodB));
    var dt2 = new DelegateTest();
    dt2.methodA($createStaticDelegate(dt2, dt2.methodB));
};
```

**Comment by labriola** [comment]
Please note that when looking into this issue, we intentionally do _not_ wrap anonymous inline functions today and should continue to ensure we do not to be compatible with normal ActionScript scope delegation

**Comment by teotigraphix** [comment]
@labriola there is no way this will change mike, its completely different logic that looking at method call arguments.

myPromise.then(foo.resultHandler, bar);

My current fix for member access is wrapping foo.resultHandler. Is this correct or not? It wasn't doing this before, but there are two tests that fail now because I have changed member access.

If this is NOT correct, I will have to use custom logic to not make it happen.

**Comment by labriola** [comment]
Mike,

Okay, its likely just my misunderstandings of the internals but these all seem like method calls to me. I completely trust you so just to clarify, this is existing behavior which should be preserved:

```
linkNode.click( handleLocationClick );
linkNode.click( function( e:Event ):void {
   Window.console.log("Handle event")
});
```

becomes

```
    this.linkNode.click($createStaticDelegate(this, this.handleLocationClick));
    this.linkNode.click(function(e) {
        console.log("Handle event");
    });
```

However today:

```
linkNode.click( other.eventHandler );
```

yields:

```
this.linkNode.click(other.eventHandler);
```

and this should be wrapped and delegated to the scope in which this function exists.

```
this.linkNode.click($createStaticDelegate(other, other.eventHandler));
```

Agreed?
Mike

**Comment by teotigraphix** [comment]
Yes, agreed. anonymous functions are not even in the equation.

All I mean was there are two instances in the demo app that will get delegates now on the Promise.then() call. Maybe they work right now because scope was not an issue.

That is all I am saying. But the above IS correct, I am ONLY transforming things in the method call argument container.

**Comment by labriola** [comment]
I would not expect any changes in the demo app. can you point me to what would change?

**Comment by labriola** [comment]
Just looked through everything. If the changes you are seeing are both where we are calling a parser, TargetsService for example, then I agree. We were lucky because the scope didnt matter. If its something else,let me know

**Comment by teotigraphix** [comment]
Yes the two cases are LabService and TargetService "parseResult" will be wrapped in both cases.

**Comment by labriola** [comment]
Perfect, sounds good to me

**Comment by teotigraphix** [comment]
Below is the new output;

``` javascript
parserPromise = promise.then($createStaticDelegate(this, this.targets.parseResult));
```

**Comment by labriola** [comment]
No, that would be a problem. Look at the example I showed above. The delegation needs to be to the scope where the method exists. 

```
parserPromise = promise.then($createStaticDelegate(this.targets, this.targets.parseResult));
```

**Comment by teotigraphix** [comment]
ok, I knew I was missing something and this was obvious.

I can fix that easily right now.

**Comment by teotigraphix** [comment]
that is settled, fixed. scope of the Function's Type is passed as the 1st argument in the delegate.

**Comment by teotigraphix** [comment]
commit 4f78366ac2afa39aa574f4ba40a9962b74c437c3
