### ISSUE TITLE
Incremental compiler may still be outputting more than needed.

### ISSUE THREAD

**Issue by labriola** [RandoriAS/randori-compiler#32]
This is more of an investigation than an issue. If I change TargetsMediator in the demo with the newest compiler version, it regens TargetsMediator, but also TargetsService, GenericJSONParser, HMSSBus and copies both libs.

Those are all the files directly referenced via a concrete type in TargetsMediator. Wondering if this is a bug or expected.

**Comment by teotigraphix** [comment]
@labriola this is expected. and now that I think of it being away from the code a while, seems wrong. I was using direct dependencies. It seems like I need reverse dependencies.  

Obviously right now we are not going to have a smart enough compiler to know what changed in the TargetsMediator, but what if you changed a method name, simple compile would say recompile all classes that use this class.

And I can now see that I have this completely backwards. 

What is your take mike? What would you expect to happen for incremental compile on a simple level.

**Comment by labriola** [comment]
my take is that its backwards. i dont think we need to compile or dependencies, i think we need to compile anything that is dependent upon us

**Comment by teotigraphix** [comment]
Right, its reverse dependencies. Dyslexia, I love it. In my head I knew what I wanted, what actually happened was another story.

Do you want this fixed before you tag a release?

**Comment by labriola** [comment]
No, I think we can still get something out. Then lets try to get this issue fixed and this one I pushed to Fred : https://github.com/RandoriAS/randori-plugin-intellij/issues/51 for the next release. I think they are high priority, but I don't think we need to stop current release plans.

**Comment by teotigraphix** [comment]
I already have this fixed. As far as the other issue, I have no idea what fred is doing now. The IntelliJ build process is still foreign to me and I still think it sucks we have to wait for its 10 seconds on a rebuild when it takes our compiler 2 seconds.

So I will just push this and merge it since I have it done.

**Comment by labriola** [comment]
So I am getting sub 1 second build times. When are you seeing 10?

**Comment by labriola** [comment]
let us know when you have this merged in. We will incorporate it into the latest and greatest

**Comment by teotigraphix** [comment]
commit 5868aff1529061771bed71f6697179e79204625

**Comment by labriola** [comment]
Mike,

I am still seeing the same behavior with the latest code:

If I change TargetsMediator in the demo with the newest compiler version, it regens TargetsMediator, but also TargetsService, GenericJSONParser, HMSSBus and copies both libs.

**Comment by teotigraphix** [comment]
I have nothing to do with the libs being copied, that is the plugin still. 

Are you sure, I am for sure using reverse dependencies Mike. So the fact that HMSSBus is there is very fishy.

**Comment by labriola** [comment]
Roland had the same result when he tried

**Comment by teotigraphix** [comment]
https://github.com/RandoriAS/randori-compiler/pull/34
