### ISSUE TITLE
Classes which are marked as export false but provided a name do not get correctly inserted in injection data

### ISSUE THREAD

**Issue by labriola** [RandoriAS/randori-compiler#35]
Take for example this class definition:

```
[JavaScript(export="false",name="randori.signal.SimpleSignal")]
public class TimeSignal {
}
```

If I instantiate TimeSignal, I correctly get:

```
var x = new randori.signal.SimpleSignal();
```

However if I ask to Inject it:

```
[Inject]
public var dataLoadStarted:TimeSignal;
```

I get this in the injection data:

```
p.push({n:'dataLoadStarted', r:0, v:null});
```

where I would expect:

```
p.push({n:'dataLoadStarted', t:'randori.signal.SimpleSignal',r:0, v:null});
```

It's possible that this is running into a contradiction with other rules we explicitly setup. If that's the case, let me know and we can figure out the right path forward.

**Comment by teotigraphix** [comment]
Nope;

Without even looking at code I bet I can guess exactly what is happening. I created a Utility method that takes care of resolving export and type names. The problem I see here is that the FooterEmitter is not using the correct name/type resolver method.

Sorry about that.

**Comment by labriola** [comment]
No worries. Just wanted to make sure it wasnt a problem I caused by some other instruction

**Comment by teotigraphix** [comment]
commit 82fc713ed93d7a52fc1b5b665911473081d64b65
