### ISSUE TITLE
Name attribute of JavaScript annotation not being correctly respected with static classes

### ISSUE THREAD

**Issue by labriola** [RandoriAS/randori-compiler#37]
Let's say I have a class like the following:

```
package behaviors.tabs {
[JavaScript(export="false",name="my.name.is.Mike")]
public class TheStaticClass {
    public static function blah() {

    }
    public function TheStaticClass() {
    }
}
}
```

When I use this class in ActionScript, I would use it like:  

TheStaticClass.blah();

I would expect though than on an export, it would use the name attribute, so I would expect code that looked like this in the JS:

my.name.is.Mike.blah();

Instead I get this:

TheStaticClass.blah();

So, it seems to be ignoring the name in these cases. This is a bug for sure... however... I am also worried that when you fix it it might expose errors in the current libraries, especially jQuery as I believe we have mistakes in some of the name attributes and the libraries are only working because the name is being ignored or handled somehow differently.

Mike

**Comment by teotigraphix** [comment]
Actually, I think this has to do with not taking the package name into account.

I am going to tackle the other issue this week that is just testing all of this stuff in one test class, then I can nail down all expected functionality

**Comment by teotigraphix** [comment]
commit  5ebdbe8 

This didn't break anything Mike, it just wasn't implemented in MemberAccess
