### ISSUE TITLE
CSS Bug: Not working without space after class name

### ISSUE THREAD

**Issue by leifwells** [RandoriAS/randori-compiler#4]
When building the code for Lesson 6 in the wiki (https://github.com/RandoriAS/randori-plugin-intellij/wiki/Lesson-6:-Managing-Randori-with-CSS) I typed along with the lesson. Since the IDE doesn't seem to help with CSS my code looked like this:

.simpleApp{

This code wasn't compiled and the correct behavior was not occurring. Changing the code to match the example exactly fixed the issue:

.simpleApp {

Please note the space after the class name.

Also note, I had to clear my cache to recreate the issue when double checking the issue before filing this bug.

**Comment by teotigraphix** [comment]
@leifwells Currently there is zero css code in the plugin. That means any css auto complete bugs are in IntelliJ.

**Comment by teotigraphix** [comment]
realized this is not an issue with this module, closing
