### ISSUE TITLE
Moving around classes

### ISSUE THREAD

**Issue by jonbcampos** [RandoriAS/randori-compiler#40]
I moved some classes around (behaviors.css out of src) along with source code (went from src.js.{folders} to src.{folders}) and my imports seemed to disappear. The randori.\* stayed. The rest were wiped out.

**Comment by teotigraphix** [comment]
This has to do with the plugin. I can't fix this in relation to the compiler.

**Comment by jonbcampos** [comment]
Sorry. I just guessed where it needed to go.

**Comment by teotigraphix** [comment]
This is not relevant to the compiler, so closing it as stated, belongs in the plugin issues.
