### ISSUE TITLE
Cross-compile parseInt() properly

### ISSUE THREAD

**Issue by rolandzwaga** [RandoriAS/randori-compiler#41]
Using this article as a reference:

http://jslinterrors.com/missing-radix-parameter/

It might be a good idea to emit parseInt() with the second argument in case it isn't defined in the AS3 sources.

**Comment by teotigraphix** [comment]
ok, checked the article, seems easy enough.

I think I will create some type on 'plugin' for this type of stuff, IE parameter checks, type definition usage etc. That way adding things like this in the future will be easy

**Comment by teotigraphix** [comment]
commit 4fb4861
