### ISSUE TITLE
using for each() to loop trough an array

### ISSUE THREAD

**Issue by gert789** [RandoriAS/randori-compiler#43]
When looping trough an array using for each(), Randori puts the array key in the variable, instead the corresponding value.

```
var x:Array = ["e","f"];
for each(var s:String in x){
    Window.console.log( s );
}
```

The console output will now be 

```
> 0
> 1
```

Using the jQuery foreach function works fine.

```
var x:Array = ["e","f"];
x.forEach(function (s:String):void {
    Window.console.log( s );
});
```

Output:

```
> e
> f
```

**Comment by teotigraphix** [comment]
Yes, this was something that was glossed over in the initial implementation of the compiler, will be fixed.

**Comment by teotigraphix** [comment]
commit 2ee9851
