### ISSUE TITLE
RegEx literal variable improperly compiled

### ISSUE THREAD

**Issue by bschmidtke** [RandoriAS/randori-compiler#47]
Correct: 
ActionScript
var fooPattern:RegExp = new RegExp("foo");

generates JS:
 var fooPattern = new RegExp("foo");

Incorrect:
ActionScript
var barPattern:RegExp = /bar/;

generates JS:
 var barPattern:RegExp = bar;

Resulting in "'bar' not found" during code execution.

**Comment by teotigraphix** [comment]
Ok, this is a weird thing with the Falcon framework and I know exactly where this bug is.

**Comment by teotigraphix** [comment]
commit  7812fc3
