### ISSUE TITLE
Allow JavaScriptConstructor factoryMethod to propagate ctor arguments

### ISSUE THREAD

**Issue by rolandzwaga** [RandoriAS/randori-compiler#53]
We need some way to tell the compiler to pass the arguments send to the AS3 constructor to the factoryMethod in the JS output.
I.e. if we have a JavaScriptConstructor annotation like this:
[JavaScriptConstructor(factoryMethod="MyClass.create()")]

And an AS3 constructor like this:

var obj:MyClass = new MyClass("text", 1, true);

In this case we need to be able to tell the compiler to add the ctor args to the MyClass.create() method.

My suggestion is this:
[JavaScriptConstructor(factoryMethod="MyClass.create(...args)")]

I'm hoping this is easily parseable on the compiler side of things. I think syntactically this is the easiest and most readable, not sure if its easily implementable though :)

Please advice :)

**Comment by teotigraphix** [comment]
Ok, I think I understand what you wanted.

Using the var args ... I am replacing the ...args with the passed arguments. The replacement is smart enough that it is only looking for the ... and replaces everything inside the parens.

So a class annotated with;

```
[JavaScriptConstructor(factoryMethod="MyClass.create(...args)")]
```

Using in the client class;

```
var obj:JavaScriptConstructor1 = new JavaScriptConstructor1("text", 1, true);
```

Will produce the following, is this what you are after? If it is I can commit this change with tests.

```
functional.tests.annotation.JavaScriptConstructorTest.prototype.test_var_args = function() {
    var obj = MyClass.create("text", 1, true);
}
```

**Comment by teotigraphix** [comment]
commit      62d5326
