### ISSUE TITLE
improper translation between AS3 -> JS with getters and setters

### ISSUE THREAD

**Issue by jonbcampos** [RandoriAS/randori-compiler#67]
I have this line of code:

```
selectedMovieModel.selectedMovie.similars = value;
```

Which turns into this line of code:

```
this.selectedMovieModel.set_selectedMovie.similars = value;
```

But should be:

```
this.selectedMovieModel.get_selectedMovie.similars = value;
```

**Comment by labriola** [comment]
Jon. I agree it looks like a bug but are you sure about your suggested correct output. Looks even more wrong

**Comment by jonbcampos** [comment]
@labriola well it can be whatever you think. basically I was just thinking the getter should get called instead of the setter

**Comment by labriola** [comment]
Jon. Really look at what you wrote though. You are assigning to a getter. I wasn't you to edit so there its no confusion on Monday and mike can tackle it

**Comment by labriola** [comment]
Never mind. I was mis interpreting your code

**Comment by jonbcampos** [comment]
well I guess it should be

this.selectedMovieModel.get_selectedMovie().similars = value;

**Comment by labriola** [comment]
No. On second thought go review. Your output doesn't match your as codes intention

**Comment by labriola** [comment]
your actionscript code sets list.data with the data from .... similars.

why would your javascript code set it? just look at your as versus proposed js for a moment. they are night and cheeseburger

**Comment by jonbcampos** [comment]
I'm not sure what you're going for.... nevermind. I see that I copied the wrong segment of code. editing.

**Comment by jonbcampos** [comment]
@labriola edited

**Comment by labriola** [comment]
perfect. thanks. @teotigraphix is going to love you for this one ;)

**Comment by jonbcampos** [comment]
@labriola my first thought was that I should change my coding style but then I thought that this should be supported.

**Comment by labriola** [comment]
it should be fixed, but in the short term you see the workaround, yes?

**Comment by jonbcampos** [comment]
I do but I'll probably wait. This is the second change necessary for completion. Beyond these things everything is done with the demo. (And since it's a demo it is lower on the priority scale)

**Comment by teotigraphix** [comment]
commit 1b08e7e
