### ISSUE TITLE
Using Assignment Operators with Properties causes a runtime error.

### ISSUE THREAD

**Issue by sgriffith** [RandoriAS/randori-compiler#69]
Reposted from randori-sdk issues:

A runtime error occurs when I use an assignment operator with a property. The application compiles successfully even though an error occurs in the generated javascript. 

the following Actionscript code:

protected var _x:Number = 0;
public function get x():Number
{
return _x;
}
public function set x( value:Number ):void
{
_x = value;
}

x += 5

generates the follwing Javascript code:

this._x = 0;

Class.prototype.get_x = function() {
return this._x;
};

Class.prototype.set_x = function(value){
this._x = value;
};

this.get_x() += 5;  <<<= gives an error at runtime.

If more information is needed, including the .as file, please let me know.

Thanks.

**Comment by teotigraphix** [comment]
BTW, this is not a production bug perse', its an implementation bug. The compiler is generating the correct code for what it thinks is going on, its that this is an edge case where transforming variables into functions has to be worked around.

Since the getter isn't returning a reference, its returning the value, this is where you are getting the error in the browser. This needs to be discussed @rolandzwaga and @labriola .

**Comment by rolandzwaga** [comment]
@labriola @teotigraphix would this be acceptable output:

this.set_x(this.get_x() + 5) ?

**Comment by teotigraphix** [comment]
yeah I was thinking the same thing, but this opens up a huge can of worms because ALL assignment operators need to be treated with this solution.

**Comment by rolandzwaga** [comment]
so, that means +=, -=, *=, |=, &=, right?

**Comment by rolandzwaga** [comment]
yet, only when used in combination with a getter

**Comment by rolandzwaga** [comment]
ow, and also only _compound_ assignment operators, right? regular operators don't apply to this issue, imho
since 'this.get_x() + 5' won't throw an error.

**Comment by teotigraphix** [comment]
yeah its only compound assignment since you "need something to pass the new value to".

**Comment by teotigraphix** [comment]
now that I think about it, unary stuff might be in peril as well :) (inc/dec -- ++)

**Comment by rolandzwaga** [comment]
Yea, I'm afraid you're right actually. So you were right about that can of worms...

**Comment by teotigraphix** [comment]
I think I am versed enough in the compiler(I might have to ask to original developer) That I might have a mix master mike solution for this that is not complicated. We will see. :8ball:

**Comment by rolandzwaga** [comment]
I believe in you :)

**Comment by teotigraphix** [comment]
commit      a7471bd
