### ISSUE TITLE
When an optional parameter's default value is defined as 'undefined', it should be omitted from the output

### ISSUE THREAD

**Issue by rolandzwaga** [RandoriAS/randori-compiler#70]
In JavaScript there is no such thing as a default value for a method argument. Some JS frameworks do define default values, but these are assigned by the framework itself when the argument isn't passed in.
In AS3 we still need to generate a method that defines all of the possible arguments, but we need to be able to just set the default argument to 'undefined' and have the compiler just ignore that value in the output.

In practice, an AS3 method that looks like this:

function myMethod(myString:String, myInt:int=undefined, myBoolean:Boolean=undefined);

that is invoked like this:

myMethod("MyStringValue");

Should result in this output:

myMethod("MyStringValue");

so, _not_ like this:

myMethod("MyStringValue", undefined, undefined);

So, this only applies to optiona arguments that have 'undefined' as their default value, any other value _should_ be output.

**Comment by rolandzwaga** [comment]
Actually, to change into a more general discussion about optional arguments. Currently, optional arguments get satisfied whithin the method body, right?
So, this method:
function myMethod(str:String='bla'):void;
gets called like this:
myMethod();
and in the generated method there is this in the body:

if (str == null) {
  str = 'bla';
}

(Or something along those lines)

The way SharpKit handles this might be a better appraoch, it satisfies the default values at invocation.
So, the JS output invoking the method is actually output like this:

myMethod('bla');

This will save us a bunch of if statements in the method body that need to be processed upon its invocation. And there the rule would apply that if the default value is 'undefined', the argument value gets omitted completely in the invoking code.
So:

function myMethod(str:String=undefined):void;

would result in an invocation like this:

myMethod();

**Comment by teotigraphix** [comment]
Hmm, sounds like more work. :)

**Comment by teotigraphix** [comment]
commit c5cdafd
