### ISSUE TITLE
Create a workflow for generating a Randori specific builtin.swc

### ISSUE THREAD

**Issue by rolandzwaga** [RandoriAS/randori-compiler#76]
A builtin.swc that leaves out all Flash specific classes and includes the annotion base classes by Mike S.
We'll need some build scripts and whatnot to make this happen.

**Comment by teotigraphix** [comment]
@rolandzwaga so this build stuff will be in the randori-sdk repo? Since that is where the builtin.swc needs to be anyways.

**Comment by rolandzwaga** [comment]
No, we have a nice tools repository for such things :)

https://github.com/RandoriAS/randori-tools/tree/develop/RandoriBuiltin
