### ISSUE TITLE
explicit this not generated correctly with same name as local variable or right side

### ISSUE THREAD

**Issue by teotigraphix** [RandoriAS/randori-compiler#79]
```

class Foo() {

  private var bar:Bar;

  function doThing() {
    var bar:Bar = this.bar; //fails, generates bar = bar.
  }

  function Foo( bar:Bar ) {
    this.bar = bar;//works fine, generates this.bar = bar;
  }
}
```

**Comment by teotigraphix** [comment]
@labriola I have tested this 3 different ways. Are you using the plugin? If so this is probably fixed now since the compiler code is light years a head right now with fixes.

Did you find this in the plugin?

```
    public function explicit_this_rhs():void
    {
        var field3:ClassB = this.field3;
        var accessor1:int = this.accessor1;
        var field1:String = this.field1;
    }
```

produces;

```
demo.foo.ClassB.prototype.explicit_this_rhs = function() {
    var field3 = this.field3;
    var accessor1 = this.get_accessor1();
    var field1 = this.field1;
}
```

As far as I can see, this has been fixed.

**Comment by labriola** [comment]
I believe I can replicate with the command line compiler. Let me try

**Comment by labriola** [comment]
Not able to replicate via the command line latest. Interesting. Okay close this for now and if I find a replication case I will open a new ticket
