### ISSUE TITLE
parseInt() 

### ISSUE THREAD

**Issue by teotigraphix** [RandoriAS/randori-compiler#83]
@rolandzwaga Now that we are building the bultin.swc, when all is implemented do I take out the hack for parseInt()?

IE adding null for radix

**Comment by rolandzwaga** [comment]
Eventually, yea, I guess in the builtin we can set the default radix to 10 instead of null.

**Comment by labriola** [comment]
that wont work unless mike also implements the code that does default assignment in method invocation. built in is just another shim. it contributes no code at runtime

**Comment by rolandzwaga** [comment]
Mike has just implemented default assignment in method invocation, that's why he asked this question, I'm guessing :)

**Comment by teotigraphix** [comment]
commit c5cdafd, its safe right now using the actual default arg logic, it places 0 until we use the new builtin.swc with rolands change
