### ISSUE TITLE
Add support for metadata classes

### ISSUE THREAD

**Issue by rolandzwaga** [RandoriAS/randori-compiler#9]
The compiler will need to be able to check metadata @compile time, so that typos in metadata can be reported.
A metadata class should implement a particular interface that is part of the Randori SDK.

These classes will only be parsed, so not cross-compiled.

The interface would determine the name and the arguments and their types for a specific metadata annotation, the interface would simply be a marker:

public interface IMetadata {
}

The implementation could look like this:

public class JavaScript implements IMetadata {
  public var export:Boolean;
  public var name:String;
  pulbic var mode:Vector.<String> = new <String>["json","global","prototype"];
}

So, the name of the implementing class will determine the name of the metadata, the properties determine the arguments and their types.
So the example class would be able to describe this metadata:
[JavaScript(export="false",name="Object",mode="json")]

These classes could be read into structures which can be used to validate the annotations @compiletime. Further more, these same structures can be exposed to the IDE so that they can be used to populate codecompletion lists.

**Comment by teotigraphix** [comment]
this is issue#20, so I am closing this
