### ISSUE TITLE
Various Compiler Issues: static RegExp, object, and multiple class definitions

### ISSUE THREAD

**Issue by renaun** [RandoriAS/randori-compiler#93]
Here is the AS3 class with all the issues in it:

```
package bug
{
public class BugA
{
    protected static const REGEXP:RegExp    = /^\s+|\s+$/g;
    private static const SAMPLEMAP:Object = new Object();//             = new Dictionary();
    private static const D2:String                          = "a2d";

    public function BugA()
    {
    }

    public function init():void
    {
        var line:String = "";
        line = line.replace( REGEXP, "" );

        SAMPLEMAP[ D2 ] = new Sampler(D2);
    }
}
}
{
class Sampler
{
    private var _name:String;

    public function get name():String   { return _name; }

    public function Sampler( name:String )
    {
        _name = name;
    }
}
}
```

This was tested with 0.2.4.8.

Issue #1: REGEXP is blank in JS code:
line = line.replace(, "");

Issue #2: SAMPLEMAP[ D2 ] = new Sampler(D2); turns in to the JS code:
[a2d] = new Sampler(a2d);
It should be something like:
SAMPLEMAP[a2d] = new Sampler(a2d);

Issue #3: Sampler class declared in the same file:
The extra declared classes in the file (aka: Sampler) are not generated and cause 404 error. Need to also apply the package of the main class probably instead of assuming its just a class with no package.

**Comment by teotigraphix** [comment]
commit 050d9e8

Moving internal class issue to a new issue.
