### ISSUE TITLE
Bug: Static Strings with full Path and Namespaces

### ISSUE THREAD

**Issue by renaun** [RandoriAS/randori-compiler#97]
Here is the code to recreate the bugs, create a folder called bug and put these two files in it:

bug/bug_internal.as:
package bug
{
public namespace bug_internal;
}

bug/BugB.as:
package bug
{
import bug.bug_internal;
public class BugB
{
    public static const CONNECT : String = "connect";

```
public function cb():void { }

public function init():void
{
    this.addEventListener(bug.BugB.CONNECT, cb); // bug
    this.addEventListener(BugB.CONNECT, cb); // fine

    BugB.bug_internal::staticInternalTest();
}

public function addEventListener(type:String, callback:Function):void { }

bug_internal static function staticInternalTest():String
{
    return "hi";
}
```

}
}

Here is the JS output snippet of the full path to static const string error:
this.addEventListener(bug.BugB."connect", $createStaticDelegate(this, this.cb)); // incorrect
this.addEventListener(bug.BugB.CONNECT, $createStaticDelegate(this, this.cb)); // correct

The AS3 namespace generate codes that throws a JS runtime error with code that looks like:
bug.BugB.bug_internal::staticInternalTest();

I assume that the namespaces can just be ignored but not sure if you want to handle them differently.

**Comment by teotigraphix** [comment]
commit 7349a90
