### ISSUE TITLE
Bug: Static function reference error

### ISSUE THREAD

**Issue by renaun** [RandoriAS/randori-compiler#98]
Here is the code to reproduce:
package bug
{ 
public class BugC
{
    private static var initialized:Boolean = false;

```
public function BugC() {    
    if (!initialized)
        init();
}

static private function init():void { }
```

}
}

Snippet of the JS output looks like:
bug.BugC = function() {
    this.initialized = false;
    if (!bug.BugC.initialized)
        init();
};

bug.BugC.initialized = false;

bug.BugC.init = function() {
};

But the init() call should look like:
bug.BugC.init()
just like the static property of "initialized"

**Comment by teotigraphix** [comment]
commit 7349a90
